export const dynamic = 'force-dynamic';
// GET    /api/account — export all user data as JSON
// DELETE /api/account — delete account (requires re-auth confirmation)

import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabaseClient, createServiceClient } from '@/lib/supabase';
import { accountLimiter, checkUserRate } from '@/lib/rateLimit';
import { safeError, auditLog, auditLogDb } from '@/lib/security';

// ─── Data Export ──────────────────────────────────────────────
export async function GET(req: NextRequest) {
  try {
    const supabase = await createServerSupabaseClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return safeError('GET /api/account', 'Unauthorized', 401);

    const blocked = await checkUserRate(accountLimiter, user.id);
    if (blocked) return blocked;

    const db = createServiceClient();
    const userId = user.id;

    const [
      profileRes, eventsRes, alertsRes, conversationsRes,
      checkInsRes, pointsRes, milestonesRes, segmentsRes,
      windowsRes, nudgesRes,
    ] = await Promise.all([
      db.from('users').select('name, email, goals, monitoring_enabled, streak_mode, timezone, check_in_frequency, created_at').eq('id', userId).single(),
      db.from('events').select('category, severity, platform, app_name, timestamp').eq('user_id', userId).order('timestamp', { ascending: false }),
      db.from('alerts').select('sent_at, email_sent, sms_sent').eq('user_id', userId).order('sent_at', { ascending: false }),
      db.from('conversations').select('completed_at, outcome, notes').eq('user_id', userId),
      db.from('check_ins').select('status, sent_at, user_mood, partner_mood').eq('user_id', userId).order('sent_at', { ascending: false }),
      db.from('trust_points').select('points, action, note, created_at').eq('user_id', userId).order('created_at', { ascending: false }),
      db.from('milestones').select('milestone, unlocked_at').eq('user_id', userId),
      db.from('focus_segments').select('date, segment, status, flag_count').eq('user_id', userId).order('date', { ascending: false }),
      db.from('vulnerability_windows').select('label, start_hour, end_hour, day_of_week').eq('user_id', userId),
      db.from('nudges').select('trigger_type, message, severity, sent_at, acknowledged').eq('user_id', userId).order('sent_at', { ascending: false }),
    ]);

    // Exclude sensitive fields (IDs, internal references)
    // Fetch audit log too
    const auditRes = await db.from('audit_log')
      .select('action, metadata, ip_address, created_at')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })
      .limit(500);

    const exportData = {
      _meta: {
        exported_at: new Date().toISOString(),
        format_version: '1.0',
        description: 'Complete data export from Be Candid. This file contains all personal data stored about you.',
        data_categories: {
          profile: 'Your account information, goals, and preferences',
          events: 'Flagged screen activity events (category, severity, platform, timestamp — no URLs stored)',
          alerts: 'Notifications sent to your partner (timestamps and delivery status)',
          conversations: 'Accountability conversation records and outcomes',
          check_ins: 'Check-in history with mood assessments from you and your partner',
          trust_points: 'Points earned for focused behavior and completed conversations',
          milestones: 'Achievements and badges unlocked',
          focus_segments: 'Daily morning/evening focus tracking (focused or distracted)',
          vulnerability_windows: 'Scheduled high-risk time windows you configured',
          nudges: 'Proactive notifications generated by pattern detection',
          audit_log: 'Security log of account actions (logins, changes, exports)',
        },
        retention: 'All data is retained until you delete your account. You can request deletion at any time via Settings > Danger Zone or DELETE /api/account.',
        contact: 'For data questions, email privacy@becandid.io',
      },
      profile: profileRes.data,
      events: eventsRes.data ?? [],
      alerts: alertsRes.data ?? [],
      conversations: conversationsRes.data ?? [],
      check_ins: checkInsRes.data ?? [],
      trust_points: pointsRes.data ?? [],
      milestones: milestonesRes.data ?? [],
      focus_segments: segmentsRes.data ?? [],
      vulnerability_windows: windowsRes.data ?? [],
      nudges: nudgesRes.data ?? [],
      audit_log: auditRes.data ?? [],
    };

    await auditLogDb(db, { action: 'account.exported', userId });

    return new NextResponse(JSON.stringify(exportData, null, 2), {
      headers: {
        'Content-Type': 'application/json',
        'Content-Disposition': `attachment; filename="be-candid-export-${new Date().toISOString().split('T')[0]}.json"`,
      },
    });
  } catch (err) {
    return safeError('GET /api/account', err);
  }
}

// ─── Account Deletion ─────────────────────────────────────────
export async function DELETE(req: NextRequest) {
  try {
    const supabase = await createServerSupabaseClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return safeError('DELETE /api/account', 'Unauthorized', 401);

    const blocked = await checkUserRate(accountLimiter, user.id);
    if (blocked) return blocked;

    const body = await req.json().catch(() => ({}));

    // Require explicit confirmation string
    if (body.confirmation !== 'DELETE_MY_ACCOUNT') {
      return NextResponse.json(
        { error: 'Send { "confirmation": "DELETE_MY_ACCOUNT" } to confirm' },
        { status: 400 }
      );
    }

    // Require password re-verification for deletion
    if (!body.password) {
      return NextResponse.json(
        { error: 'Password required for account deletion' },
        { status: 400 }
      );
    }

    // Re-authenticate to verify identity
    const { error: reAuthError } = await supabase.auth.signInWithPassword({
      email: user.email!,
      password: body.password,
    });

    if (reAuthError) {
      return NextResponse.json(
        { error: 'Password verification failed' },
        { status: 403 }
      );
    }

    const db = createServiceClient();
    const userId = user.id;

    // Audit log BEFORE deletion (audit_log.user_id is SET NULL on delete,
    // so the row survives for compliance even after the user is gone)
    await auditLogDb(db, {
      action: 'account.deleted',
      userId,
      metadata: { email: user.email },
    });

    // Delete user row — all related data is removed via ON DELETE CASCADE
    // at the database level (events, alerts, conversations, check_ins,
    // partners, trust_points, milestones, focus_segments, nudges,
    // vulnerability_windows, encouragements, user_sessions, etc.)
    await db.from('users').delete().eq('id', userId);

    // Remove the auth.users entry last
    await db.auth.admin.deleteUser(userId);

    return NextResponse.json({ success: true, message: 'Account and all data permanently deleted.' });
  } catch (err) {
    return safeError('DELETE /api/account', err);
  }
}
