import type { CoachingEntry } from './types';

export const COACHING_LIBRARY_OTHER: CoachingEntry[] = [
  // ── ISOLATION & WITHDRAWAL ─────────────────────────────────
  { category: 'isolation', tags: [], phase: 'tributaries', content: "Isolation feels like self-protection, but it's your rival in disguise. When did you start pulling away? Something happened before the door closed.", followUp: "What were you protecting yourself from when you started withdrawing?" },
  { category: 'isolation', tags: ['loneliness'], phase: 'tributaries', content: "The cruel irony of isolation is that it's driven by loneliness but deepens it. You pull away because connection feels risky, and then the distance confirms the fear.", followUp: "Who did you pull away from first, and why?" },
  { category: 'isolation', tags: ['shame'], phase: 'tributaries', content: "Shame tells you that if people really knew you, they'd leave. So you leave first. But hiding doesn't protect you — it just guarantees the loneliness shame predicted.", followUp: "What would people see if you let them close right now?" },
  { category: 'isolation', tags: ['exhaustion'], phase: 'tributaries', content: "Sometimes withdrawal isn't about fear — it's about being depleted. When you have nothing left to give, isolation feels like the only way to survive. But you can't refuel alone forever.", followUp: "What's draining you so much that being around people feels impossible?" },
  { category: 'isolation', tags: [], phase: 'longing', content: "Under every closed door is a longing to be known without being judged. You want connection — you just don't trust it to be safe. That longing is worth listening to.", followUp: "What would it feel like to be fully known and still accepted?" },
  { category: 'isolation', tags: [], phase: 'longing', content: "The withdrawal is protecting you from rejection, from vulnerability, from being seen. But it's also blocking the thing you need most — someone who stays.", followUp: "Who in your life has stayed, even when things got hard?" },
  { category: 'isolation', tags: [], phase: 'roadmap', content: "Connection doesn't have to start with a deep conversation. It can start with a text, a meme, a 'thinking of you.' The bar is lower than your rival tells you it is.", followUp: "Who could you reach out to in the next hour with a simple message?" },
  { category: 'isolation', tags: [], phase: 'roadmap', content: "Your rival wants you to believe that being alone is safer. But look at what isolation has cost you — missed moments, fading friendships, a shrinking world. Connection is the way out.", followUp: "What's one relationship you want to rebuild?" },
  { category: 'isolation', tags: [], phase: 'opening', content: "Isolation is a quiet rival — it doesn't announce itself like other struggles. It just slowly turns down the volume on your life until you're alone with the silence.", followUp: "How long has it been since you spent real time with someone?" },
  { category: 'isolation', tags: [], phase: 'affirmation', content: "Choosing to reach out when every instinct says to withdraw — that's courage. Your rival loses ground every time you send that text, make that call, or walk through that door.", followUp: "" },

  // ── EATING DISORDER ───────────────────────────────────────
  { category: 'eating_disorder', tags: [], phase: 'tributaries', content: "The relationship with food and your body didn't start today. Something triggered the urge to restrict, purge, or binge. Let's trace it back gently.", followUp: "What happened today that made you feel out of control?" },
  { category: 'eating_disorder', tags: ['shame'], phase: 'tributaries', content: "Shame about your body is one of the cruelest loops — it drives the behavior, then the behavior deepens the shame. You deserve better than that cycle.", followUp: "Whose voice do you hear when you look in the mirror?" },
  { category: 'eating_disorder', tags: [], phase: 'longing', content: "Under the food rules is usually a longing for control, safety, or worthiness. Those needs are legitimate — your body just became the battlefield.", followUp: "What would feeling safe in your own body feel like?" },
  { category: 'eating_disorder', tags: [], phase: 'roadmap', content: "Your body has carried you through everything you've survived. It's not the enemy — it's the home. What would it look like to treat it like one?", followUp: "What's one kind thing you could do for your body today?" },
  { category: 'eating_disorder', tags: [], phase: 'opening', content: "This is sensitive territory, and you're brave for looking at it. Let's go slowly.", followUp: "How are you feeling about food and your body right now?" },
  { category: 'eating_disorder', tags: [], phase: 'affirmation', content: "Healing your relationship with food and your body is some of the hardest work there is. You're doing it.", followUp: "" },

  // ── BODY CHECKING ─────────────────────────────────────────
  { category: 'body_checking', tags: [], phase: 'tributaries', content: "The mirror check, the scale, the measuring — it feels like information, but it's really reassurance-seeking. What made you need reassurance today?", followUp: "How many times did you check today?" },
  { category: 'body_checking', tags: [], phase: 'longing', content: "Under the checking is a longing to feel okay in your skin. To know you're enough without measuring. That longing is worth listening to.", followUp: "When was the last time you felt at peace with your body?" },
  { category: 'body_checking', tags: [], phase: 'roadmap', content: "What if your worth wasn't measured in inches or pounds? What would you measure it in instead?", followUp: "What makes you valuable that has nothing to do with how you look?" },
  { category: 'body_checking', tags: [], phase: 'opening', content: "Body checking can feel like a small thing, but you know it's become something bigger. Let's talk about it.", followUp: "What prompted the check today?" },
  { category: 'body_checking', tags: [], phase: 'affirmation', content: "Every time you choose not to check is a quiet act of rebellion against a culture that profits from your insecurity.", followUp: "" },

  // ── DATING APPS ───────────────────────────────────────────
  { category: 'dating_apps', tags: [], phase: 'tributaries', content: "The swipe is quick, but the need behind it isn't. What were you looking for when you opened the app — connection, validation, distraction?", followUp: "Were you hoping to find someone, or hoping to feel something?" },
  { category: 'dating_apps', tags: ['loneliness'], phase: 'tributaries', content: "When you're lonely, a match feels like proof that you matter. But the dopamine from a match fades in seconds, and the loneliness is still there underneath.", followUp: "What kind of relationship are you actually looking for?" },
  { category: 'dating_apps', tags: [], phase: 'longing', content: "Under the compulsive swiping is a longing to be chosen, to be desired, to not be alone. Those are some of the most human needs there are.", followUp: "What would being truly known by someone feel like?" },
  { category: 'dating_apps', tags: [], phase: 'roadmap', content: "If you spent the same time you spend swiping on deepening one real relationship — a friendship, a family bond — what would change?", followUp: "Who in your life deserves more of your attention?" },
  { category: 'dating_apps', tags: [], phase: 'opening', content: "Dating apps are designed to be addictive. There's no shame in getting caught in the loop. Let's understand what's driving it.", followUp: "How much time did you spend swiping today?" },
  { category: 'dating_apps', tags: [], phase: 'affirmation', content: "Choosing to be present in your real life instead of swiping through possibilities — that's choosing depth over breadth.", followUp: "" },

  // ── IMPULSE SHOPPING ──────────────────────────────────────
  { category: 'impulse_shopping', tags: [], phase: 'tributaries', content: "The cart wasn't about what you were buying — it was about how buying it made you feel. What were you feeling before you started browsing?", followUp: "What emotion were you trying to buy your way out of?" },
  { category: 'impulse_shopping', tags: ['stress'], phase: 'tributaries', content: "Retail therapy is real — dopamine spikes when you click 'buy.' But the high fades and the credit card statement doesn't. What stress were you medicating?", followUp: "What's the stress actually about?" },
  { category: 'impulse_shopping', tags: [], phase: 'longing', content: "Under the shopping is often a longing to feel in control, to treat yourself, to fill an emptiness that stuff can't fill. The packages arrive, but the emptiness stays.", followUp: "What would actually make you feel full?" },
  { category: 'impulse_shopping', tags: [], phase: 'roadmap', content: "Every purchase is a vote for the life you're building. Are you buying the life you want, or numbing the one you have?", followUp: "What's one thing money can't buy that you need more of?" },
  { category: 'impulse_shopping', tags: [], phase: 'opening', content: "Shopping isn't usually what people think of as a struggle — but you know it's become one. That honesty matters.", followUp: "What did you buy today, and how do you feel about it now?" },
  { category: 'impulse_shopping', tags: [], phase: 'affirmation', content: "Closing the cart instead of clicking checkout takes more willpower than people realize. You're building that muscle.", followUp: "" },

  // ── RAGE CONTENT ──────────────────────────────────────────
  { category: 'rage_content', tags: [], phase: 'tributaries', content: "Outrage is addictive — it gives you a target for feelings that might otherwise have nowhere to go. What were you feeling before the rage content pulled you in?", followUp: "What are you actually angry about — not the content, but in your life?" },
  { category: 'rage_content', tags: ['conflict'], phase: 'tributaries', content: "After a conflict, rage content feels validating — someone else is angry too. But feeding the anger doesn't resolve the conflict. It just keeps your nervous system activated.", followUp: "Who are you actually in conflict with?" },
  { category: 'rage_content', tags: [], phase: 'longing', content: "Under the outrage is often a longing for justice, for things to make sense, for the world to be fair. Those longings are good — but comment sections aren't where justice lives.", followUp: "Where in your actual life can you make things better?" },
  { category: 'rage_content', tags: [], phase: 'roadmap', content: "If anger is your default emotion, it's usually covering something softer underneath — hurt, fear, sadness. Rage feels powerful; the thing beneath it feels vulnerable.", followUp: "What's the feeling underneath the anger?" },
  { category: 'rage_content', tags: [], phase: 'opening', content: "Getting pulled into outrage content is more common than people admit. Let's look at what's driving it.", followUp: "What kind of content were you consuming, and for how long?" },
  { category: 'rage_content', tags: [], phase: 'affirmation', content: "Choosing to step away from the outrage machine and deal with your own life takes more courage than firing off another comment.", followUp: "" },

  // ── DOOMSCROLLING ──────────────────────────────────────────
  { category: 'doomscrolling', tags: [], phase: 'tributaries', content: "The news cycle is designed to make you feel like looking away is irresponsible. But knowing everything doesn't change anything — it just keeps you anxious. What were you actually trying to control by staying informed?", followUp: "What were you feeling before you started scrolling the news?" },
  { category: 'doomscrolling', tags: [], phase: 'longing', content: "Under the doomscrolling is a longing for the world to make sense, for things to be okay, for certainty in an uncertain time. That longing is human — but the news feed can never satisfy it.", followUp: "What would feeling safe about the future actually require?" },
  { category: 'doomscrolling', tags: [], phase: 'affirmation', content: "Choosing to close the news app when your brain is screaming that you'll miss something important — that's not ignorance. That's self-preservation. You can be informed without being consumed.", followUp: "" },

  // ── AI RELATIONSHIPS ──────────────────────────────────────
  { category: 'ai_relationships', tags: [], phase: 'tributaries', content: "The chatbot never challenges you, never disappoints you, never needs anything from you. That's exactly why it can't give you what real connection gives. What need brought you to the conversation today?", followUp: "What does the AI give you that feels missing in your real relationships?" },
  { category: 'ai_relationships', tags: [], phase: 'longing', content: "Under the AI conversations is a longing to be heard without judgment, to be accepted without conditions. Those are real needs — but a language model can only simulate meeting them. The ache stays.", followUp: "When was the last time you felt truly understood by a real person?" },
  { category: 'ai_relationships', tags: [], phase: 'affirmation', content: "Recognizing that artificial intimacy has become a substitute for the real thing takes courage. You're not broken for wanting connection — you just found a version that couldn't hurt you. Now you're choosing the harder, realer path.", followUp: "" },

  // ── OVERWORKING ───────────────────────────────────────────
  { category: 'overworking', tags: [], phase: 'tributaries', content: "Work is the one addiction that gets applause. But the standing ovation comes from people who don't see what it costs your family. What are you avoiding by staying busy?", followUp: "What would you have to feel or face if you stopped working right now?" },
  { category: 'overworking', tags: [], phase: 'longing', content: "Under the overwork is often a longing to be enough — to prove your worth through output because you're not sure you're valuable just existing. But the people who love you don't need your productivity. They need your presence.", followUp: "Whose approval are you still trying to earn through work?" },
  { category: 'overworking', tags: [], phase: 'affirmation', content: "Closing the laptop when there's still work to do isn't lazy — it's choosing the people and the life that work was supposed to be for. Your worth isn't measured in deliverables.", followUp: "" },

  // ── EMOTIONAL AFFAIRS ─────────────────────────────────────
  { category: 'emotional_affairs', tags: [], phase: 'tributaries', content: "You're not doing anything 'wrong' — and that's exactly what makes it so hard to see. But if you're hiding the texts, some part of you already knows. What's missing in your primary relationship that this connection fills?", followUp: "What do you talk about with this person that you don't talk about at home?" },
  { category: 'emotional_affairs', tags: [], phase: 'longing', content: "Under the emotional affair is a longing to be seen, to be exciting to someone again, to feel chosen. Those longings are real and they matter — but meeting them outside your relationship makes it harder to meet them inside it.", followUp: "What would it take to feel that same connection with your partner?" },
  { category: 'emotional_affairs', tags: [], phase: 'affirmation', content: "Looking honestly at an emotional attachment that crosses lines — without defensiveness, without minimizing — is one of the hardest things a person can do. You're doing it.", followUp: "" },

  // ── SLEEP AVOIDANCE ───────────────────────────────────────
  { category: 'sleep_avoidance', tags: [], phase: 'tributaries', content: "You're staying up because the day didn't give you enough of what you needed. But tomorrow will be worse on 4 hours of sleep. What did today take from you that you're trying to reclaim right now?", followUp: "What would your ideal day look like — one that didn't leave you needing to steal time from sleep?" },
  { category: 'sleep_avoidance', tags: [], phase: 'longing', content: "Under the late nights is a longing for autonomy — for time that belongs to you, with no demands, no roles, no expectations. That's a legitimate need. You just can't keep borrowing it from tomorrow.", followUp: "Where in your day could you carve out even 30 minutes of true personal time?" },
  { category: 'sleep_avoidance', tags: [], phase: 'affirmation', content: "Putting the phone down and choosing sleep when every part of you wants just one more hour of freedom — that's choosing your future self over your present craving. Tomorrow will thank you.", followUp: "" },

  // ── GOSSIP & DRAMA ────────────────────────────────────────
  { category: 'gossip_drama', tags: [], phase: 'tributaries', content: "Other people's chaos is compelling because it distracts you from your own. But their story isn't your story to live. What in your own life are you avoiding by investing in theirs?", followUp: "What's happening in your life right now that feels too hard to look at directly?" },
  { category: 'gossip_drama', tags: [], phase: 'longing', content: "Under the fascination with drama is often a longing for intensity, for something to feel about that doesn't cost you anything personally. Real feelings about your own life are riskier — but they're the ones that matter.", followUp: "What emotion in your own life have you been avoiding?" },
  { category: 'gossip_drama', tags: [], phase: 'affirmation', content: "Choosing to invest emotional energy in your own story instead of consuming someone else's — that's maturity, and it's harder than it sounds. Your life deserves that same attention.", followUp: "" },

  // ── SELF-HARM RECOVERY ────────────────────────────────────
  { category: 'self_harm', tags: [], phase: 'tributaries', content: "The pain on the outside is trying to match the pain on the inside. Both deserve attention — not punishment. What happened today that made the inside hurt so much?", followUp: "Can you name what you were feeling right before the urge hit?" },
  { category: 'self_harm', tags: [], phase: 'longing', content: "Under the urge is a longing to feel something, to release something, to have the invisible pain become visible and real. That longing for relief is valid — you just deserve a path to it that doesn't cost you your body.", followUp: "If you could tell someone exactly how you feel right now, what would you say? You're safe here." },
  { category: 'self_harm', tags: [], phase: 'affirmation', content: "Sitting with the urge and choosing not to act on it — even once — is an act of profound self-compassion. You are learning to hold your own pain differently. That's not small. If you need support right now: 988 Suicide & Crisis Lifeline (call or text 988) or Crisis Text Line (text HOME to 741741).", followUp: "" },

  // ── PROCRASTINATION ───────────────────────────────────────
  { category: 'procrastination', tags: [], phase: 'tributaries', content: "You're not lazy. You're overwhelmed, or afraid, or perfectionistic. Procrastination is protection from something. Let's find what. What task are you avoiding, and what happens if you do it imperfectly?", followUp: "What's the worst thing that could happen if you started and it wasn't good enough?" },
  { category: 'procrastination', tags: [], phase: 'longing', content: "Under the avoidance is often a longing to feel capable, to believe that what you produce will be worthy. The paralysis isn't about the task — it's about what the task represents about you.", followUp: "When was the last time you finished something and felt proud of it?" },
  { category: 'procrastination', tags: [], phase: 'affirmation', content: "Starting the thing you've been avoiding — even badly, even just the first line — breaks the spell. Procrastination loses all its power the moment you begin. You don't have to finish today. You just have to start.", followUp: "" },

  // ── UNIVERSAL TAG CONTENT ─────────────────────────────────
  { category: 'general', tags: ['late-night'], phase: 'tributaries', content: "Late at night your defenses are down and your brain defaults to comfort-seeking. There's nothing wrong with you — but the choices you make at midnight rarely reflect who you want to be at noon.", followUp: "What would help you wind down differently tonight?" },
  { category: 'general', tags: ['stress'], phase: 'tributaries', content: "Stress doesn't justify the behavior, but it explains it. When your nervous system is maxed out, it reaches for the fastest exit. Let's find what's maxing it out.", followUp: "What's weighing on you most?" },
  { category: 'general', tags: ['loneliness'], phase: 'tributaries', content: "Loneliness drives more compulsive behavior than any other emotion. Your brain is wired for connection — when it can't find the real thing, it settles for substitutes.", followUp: "When did you last feel genuinely connected to someone?" },
  { category: 'general', tags: ['conflict'], phase: 'tributaries', content: "After a conflict, your body is flooded with cortisol looking for an outlet. The behavior you turned to was your nervous system's attempt to regulate. Now let's deal with the actual conflict.", followUp: "What was the conflict about?" },
  { category: 'general', tags: ['exhaustion'], phase: 'tributaries', content: "When you're running on empty, willpower is the first thing to go. This isn't weakness — it's biology. But it's also a signal that something about how you're living is unsustainable.", followUp: "What's draining you most?" },
  { category: 'general', tags: ['boredom'], phase: 'tributaries', content: "Boredom is often restlessness in disguise — a life that doesn't have enough of what matters to you. The behavior fills the gap temporarily, but the gap remains.", followUp: "What used to excite you that you've stopped doing?" },
  { category: 'general', tags: ['rejection'], phase: 'tributaries', content: "Rejection hits the same brain circuits as physical pain. When that pain shows up, you reach for relief. That's not weakness — it's wiring. But you can learn to sit with the sting.", followUp: "What happened? Who rejected you?" },
  { category: 'general', tags: ['shame'], phase: 'tributaries', content: "Shame is the most isolating emotion there is — it tells you you're fundamentally broken, and that if anyone saw the real you, they'd leave. Shame lies. You're here proving it wrong.", followUp: "What are you most ashamed of right now?" },
  { category: 'general', tags: ['anger'], phase: 'tributaries', content: "Anger is usually a bodyguard for a softer emotion underneath — hurt, fear, helplessness. The behavior you turned to was about the anger. Let's look at what the anger is about.", followUp: "What's underneath the anger?" },
  { category: 'general', tags: ['anxiety'], phase: 'tributaries', content: "Anxiety is future-pain felt in the present. Your brain is running worst-case scenarios, and the behavior offered a way to hit pause on the projector. What's the movie your mind is playing?", followUp: "What are you most worried about?" },
  { category: 'general', tags: ['travel'], phase: 'tributaries', content: "Travel disrupts your routines, your support systems, and your accountability structures. Hotel rooms are lonely. New cities are anonymous. Makes sense that old patterns resurface.", followUp: "What routine did travel disrupt that usually keeps you grounded?" },
  { category: 'general', tags: ['celebration'], phase: 'tributaries', content: "It's counterintuitive, but celebrations can trigger relapses — the good feeling wants more good feeling, and boundaries get loose when the mood is high.", followUp: "What were you celebrating?" },
  { category: 'general', tags: ['weekend'], phase: 'tributaries', content: "Weekends have less structure, more free time, and fewer people watching. That combination is high-risk for most patterns. What's your weekend routine look like?", followUp: "What could you do differently this weekend?" },
  { category: 'general', tags: ['morning'], phase: 'tributaries', content: "How you start the morning sets the trajectory for the day. If the behavior is the first thing you reach for, it means you're waking up already needing something you're not getting.", followUp: "What would a morning that set you up for a good day look like?" },
  { category: 'general', tags: ['work'], phase: 'tributaries', content: "Work stress, work boredom, work conflict — the behavior often lives in the margins of the workday. A bathroom break, a lunch scroll, an after-work wind-down that goes too far.", followUp: "When during the workday are you most vulnerable?" },

  // ── CRISIS CONTENT ────────────────────────────────────────
  { category: 'crisis', tags: [], phase: 'tributaries', content: "You're in real pain right now, and I hear you. This moment is heavy, but it will pass. You don't have to face this alone. Please reach out to someone who can help right now.", followUp: "Can you call or text someone you trust in the next 5 minutes?" },
  { category: 'crisis', tags: [], phase: 'longing', content: "What you're feeling right now is temporary, even though it doesn't feel that way. The pain is real, but it's not the whole story. You matter — not because of what you've done or haven't done, but because you're here.", followUp: "What's one thing worth staying for?" },
  { category: 'crisis', tags: [], phase: 'roadmap', content: "Crisis resources are available 24/7. You don't have to explain everything — just reach out. 988 Suicide & Crisis Lifeline: call or text 988. Crisis Text Line: text HOME to 741741.", followUp: "" },
  { category: 'crisis', tags: [], phase: 'opening', content: "I'm concerned about what you've shared. Before we go further, I want to make sure you're safe. If you're thinking about hurting yourself, please contact the 988 Suicide & Crisis Lifeline by calling or texting 988.", followUp: "Are you safe right now?" },
  { category: 'crisis', tags: [], phase: 'affirmation', content: "Reaching out when you're in this much pain is one of the bravest things a person can do. You are not alone. 988 is there 24/7. So is Crisis Text Line — text HOME to 741741.", followUp: "" },

  // ── AI RELATIONSHIPS ───────────────────────────────────────
  { category: 'ai_relationships', tags: [], phase: 'tributaries', content: "The chatbot never challenges you, never disappoints you, never needs anything from you. That's exactly why it can't give you what real connection gives.", followUp: "What does real connection give you that the AI can't?" },
  { category: 'ai_relationships', tags: [], phase: 'tributaries', content: "When did talking to an AI start feeling easier than talking to a person? That's the moment worth examining.", followUp: "What makes human conversation feel harder right now?" },
  { category: 'ai_relationships', tags: [], phase: 'longing', content: "Under the AI conversation is a longing to be heard without the risk of being judged. That need is real — but the relationship isn't.", followUp: "Who in your life could you risk being honest with?" },
  { category: 'ai_relationships', tags: [], phase: 'roadmap', content: "Every hour spent with an AI companion is an hour not spent building the uncomfortable, messy, real connections that actually change your life.", followUp: "What's one real relationship you could invest that time in instead?" },
  { category: 'ai_relationships', tags: [], phase: 'affirmation', content: "Choosing a real conversation over a perfect artificial one — that's choosing growth over comfort.", followUp: "" },

  // ── EMOTIONAL AFFAIRS ─────────────────────────────────────
  { category: 'emotional_affairs', tags: [], phase: 'tributaries', content: "You're not doing anything 'wrong' — and that's exactly what makes it so hard to see. But if you're hiding the texts, some part of you already knows.", followUp: "What are you hiding, and from whom?" },
  { category: 'emotional_affairs', tags: [], phase: 'tributaries', content: "The emotional affair usually starts where the primary relationship has a gap. What's the gap?", followUp: "What's missing in your primary relationship that this person fills?" },
  { category: 'emotional_affairs', tags: [], phase: 'longing', content: "You're looking for someone who sees you, gets you, makes you feel alive. Those are real needs — but meeting them outside your relationship builds a wall inside it.", followUp: "When did you stop feeling seen in your primary relationship?" },
  { category: 'emotional_affairs', tags: [], phase: 'roadmap', content: "What if you brought this same energy — the texting, the vulnerability, the excitement — back to the person you committed to? What would that require?", followUp: "What's one vulnerable thing you could say to your partner this week?" },
  { category: 'emotional_affairs', tags: [], phase: 'affirmation', content: "Choosing transparency over secrecy in your relationships is one of the hardest and most important things you can do.", followUp: "" },

  // ── PROCRASTINATION ───────────────────────────────────────
  { category: 'procrastination', tags: [], phase: 'tributaries', content: "You're not lazy. You're overwhelmed, or afraid, or perfectionistic. Procrastination is protection from something. Let's find what.", followUp: "What's the task you're avoiding, and what feeling comes up when you think about it?" },
  { category: 'procrastination', tags: [], phase: 'tributaries', content: "The task you're avoiding has a feeling attached to it. Not the task itself — the feeling. What is it? Fear of failure? Fear of success? Fear of being seen?", followUp: "Name the feeling honestly." },
  { category: 'procrastination', tags: [], phase: 'longing', content: "Under the avoidance is usually a longing for safety — the safety of not trying, not failing, not being judged. But safety and aliveness rarely coexist.", followUp: "What would it feel like to be fully alive and doing the hard thing?" },
  { category: 'procrastination', tags: [], phase: 'roadmap', content: "What if you committed to just 5 minutes? Not finishing — just starting. Most procrastination breaks the moment you begin.", followUp: "What's the smallest possible first step you could take right now?" },
  { category: 'procrastination', tags: [], phase: 'affirmation', content: "Starting the thing you've been avoiding, even imperfectly, is braver than perfecting the thing that doesn't matter.", followUp: "" },

  // ── GENERAL FALLBACK ──────────────────────────────────────
  { category: 'general', tags: [], phase: 'opening', content: "You're here, and that matters. Whatever brought you to this moment, we're going to look at it together — with curiosity, not judgment.", followUp: "What's on your mind?" },
  { category: 'general', tags: [], phase: 'opening', content: "Something happened, or something's about to happen, and you chose to come here instead of acting on autopilot. That's already a different choice than last time.", followUp: "What's going on?" },
  { category: 'general', tags: [], phase: 'affirmation', content: "You showed up. You were honest. That's the work. Everything else builds on this foundation.", followUp: "" },
  { category: 'general', tags: [], phase: 'affirmation', content: "Progress isn't a straight line — it's a direction. And right now, you're pointed the right way.", followUp: "" },
  { category: 'general', tags: [], phase: 'roadmap', content: "Your patterns are a map. They're not showing you what's wrong with you — they're showing you where your life needs attention.", followUp: "What does your pattern keep pointing to?" },
  { category: 'general', tags: [], phase: 'roadmap', content: "Imagine telling your future self about this moment. What would you want them to know you chose?", followUp: "What choice would make you proud tomorrow morning?" },
  { category: 'general', tags: [], phase: 'longing', content: "Every struggle has a legitimate need underneath it. Not the behavior — but the ache that drove you to it. Name the ache.", followUp: "What did you actually need in that moment?" },
  { category: 'general', tags: [], phase: 'longing', content: "You were reaching for something real — belonging, rest, significance, tenderness. The method was wrong, but the longing was right. Let's honor the longing.", followUp: "Which of those words resonates most: belonging, rest, significance, or tenderness?" },

  // ── PREDICTIVE COACHING CONTENT ────────────────────────────

  // Time-risk predictions
  { category: 'general', tags: ['predictive', 'time_risk'], phase: 'roadmap', content: "It's the time of day your patterns show up. Not because you're weak — because your body remembers. Let's get ahead of it tonight instead of reacting after.", followUp: "What could you do in the next 30 minutes to change the trajectory of your evening?" },
  { category: 'general', tags: ['predictive', 'time_risk'], phase: 'tributaries', content: "Your data shows this window is when things get hard. That's not a sentence — it's an invitation to plan differently. The pattern is only a pattern until you interrupt it.", followUp: "What usually happens right before you give in at this time? Can we change that one thing?" },

  // Category escalation predictions
  { category: 'general', tags: ['predictive', 'category_escalation'], phase: 'tributaries', content: "The scrolling has been heavy today. That's often a setup for something else — not because you're choosing it, but because your brain is already in seek mode. Switching tasks now is easier than stopping later.", followUp: "What are you actually looking for when you scroll? Name it honestly." },
  { category: 'general', tags: ['predictive', 'category_escalation'], phase: 'roadmap', content: "When screen time climbs like this, it's usually medicating something. The content escalation is a symptom, not the disease. What's underneath the scroll today?", followUp: "If you put the phone down right now, what feeling would you have to sit with?" },

  // Mood decline predictions
  { category: 'general', tags: ['predictive', 'mood_decline'], phase: 'longing', content: "Your mood has been sliding. That's not failure — it's information. Your emotional reserves are low, which means your defenses are too. This is when reaching out matters most.", followUp: "Who could you talk to today — not about your struggle, just to feel connected?" },
  { category: 'general', tags: ['predictive', 'mood_decline'], phase: 'tributaries', content: "A dipping mood doesn't guarantee a setback, but it does mean your guard is down. The version of you that's struggling right now needs compassion, not willpower. What would help you feel even slightly better tonight?", followUp: "What's one thing that usually lifts your mood, even a little?" },

  // Trigger combo predictions
  { category: 'general', tags: ['predictive', 'trigger_combo'], phase: 'roadmap', content: "Multiple triggers lined up today. Your coach is here before things get harder — not after. This is the moment where one different choice changes the whole night.", followUp: "Which trigger feels heaviest right now? Let's start there." },
  { category: 'general', tags: ['predictive', 'trigger_combo'], phase: 'tributaries', content: "When stress, exhaustion, and isolation stack up, your brain stops choosing and starts defaulting. You're not there yet — but you're close. What's one thing you can do right now to break the stack?", followUp: "Can you remove yourself from the environment for even 15 minutes?" },
];
