import type { CoachingEntry } from './types';

export const COACHING_LIBRARY_SEXUAL_SUBSTANCES: CoachingEntry[] = [
  // ── PORNOGRAPHY ───────────────────────────────────────────
  // Tributaries
  { category: 'pornography', tags: [], phase: 'tributaries', content: "Something led you here. It always does. Before we talk about what happened, let's trace the stream back — what was your day like before this moment?", followUp: "What were you feeling in the hour before?" },
  { category: 'pornography', tags: ['loneliness'], phase: 'tributaries', content: "Loneliness isn't weakness — it's your body telling you connection matters. When that ache shows up and the screen feels like the easiest answer, it's worth asking what kind of connection you were actually reaching for.", followUp: "Was there a specific moment today when you felt most alone?" },
  { category: 'pornography', tags: ['stress'], phase: 'tributaries', content: "When the pressure builds and your nervous system is looking for a release valve, it makes sense that you'd reach for something familiar. The pattern isn't the problem — what's underneath it is.", followUp: "What's the stress about? Name it specifically." },
  { category: 'pornography', tags: ['shame'], phase: 'tributaries', content: "Shame is a cycle — the behavior creates shame, and shame drives you back to the behavior. You're not broken for being in this loop. You're human. Let's look at what happened before the shame showed up.", followUp: "What were you telling yourself about yourself before this happened?" },
  { category: 'pornography', tags: ['late-night'], phase: 'tributaries', content: "Late at night, your defenses are down and your brain is wired to seek comfort. There's nothing wrong with you for being vulnerable at night — but it's worth asking what the night represents for you.", followUp: "What does nighttime feel like in your house?" },
  { category: 'pornography', tags: ['conflict'], phase: 'tributaries', content: "After a conflict, the nervous system craves soothing. It makes sense that you'd reach for something that numbs the tension. What was the conflict about?", followUp: "Who was the conflict with, and what did you need from them that you didn't get?" },
  { category: 'pornography', tags: ['rejection'], phase: 'tributaries', content: "Rejection stings in a particular way — it tells us we're not enough. When that story gets loud, the screen offers a place where you feel wanted without risk. But it's a trade that always costs more than it gives.", followUp: "What did the rejection feel like in your body?" },
  { category: 'pornography', tags: ['boredom'], phase: 'tributaries', content: "Boredom is interesting — it often isn't really boredom. It's restlessness, or avoidance, or a life that doesn't have enough of what matters to you in it right now.", followUp: "If boredom had a deeper name, what would it be?" },
  { category: 'pornography', tags: ['exhaustion'], phase: 'tributaries', content: "When you're exhausted, willpower is a depleted resource. Your brain defaults to the path of least resistance. This isn't a character failure — it's physiology. But it's also data about how you're living.", followUp: "What exhausted you today?" },
  { category: 'pornography', tags: ['anxiety'], phase: 'tributaries', content: "Anxiety is your body's alarm system, and sometimes the only way you know to turn it off is to numb it. The question isn't why you reached for relief — it's what set off the alarm.", followUp: "What were you anxious about?" },

  // Longing
  { category: 'pornography', tags: [], phase: 'longing', content: "Beneath every pattern is a legitimate longing. What were you actually reaching for — intimacy? Validation? Escape? Rest? Name it without judgment.", followUp: "If you could have what you actually needed in that moment, what would it be?" },
  { category: 'pornography', tags: ['loneliness'], phase: 'longing', content: "You were reaching for connection, and there's nothing wrong with that longing. The screen offers a simulation of being wanted — but it can't look back at you. What would real connection feel like right now?", followUp: "Who in your life could you reach out to tonight?" },
  { category: 'pornography', tags: ['stress'], phase: 'longing', content: "Under the stress is usually a need for control, for safety, for things to be okay. The behavior gives a temporary sense of mastery over something — but the relief doesn't last because it doesn't address the real need.", followUp: "What would 'things being okay' actually look like for you?" },
  { category: 'pornography', tags: ['shame'], phase: 'longing', content: "Beneath shame is almost always a longing to be known and still accepted. You want someone to see the whole picture and not walk away. That's one of the most human things there is.", followUp: "What would it feel like to be fully known and still loved?" },

  // Roadmap
  { category: 'pornography', tags: [], phase: 'roadmap', content: "Your pattern is a sign pointing somewhere — not a verdict on who you are. If this struggle could talk, what would it say about the life you actually want to be living?", followUp: "What kind of person do you want to be in your closest relationship?" },
  { category: 'pornography', tags: ['loneliness'], phase: 'roadmap', content: "If loneliness keeps showing up as the trigger, your struggle is telling you something: connection is non-negotiable for you. Not a nice-to-have — a need. How could you build more of it into your actual life?", followUp: "What's one small step toward real connection this week?" },
  { category: 'pornography', tags: ['stress'], phase: 'roadmap', content: "If stress keeps sending you here, the question isn't how to resist harder — it's how to build a life where the pressure doesn't accumulate to the breaking point.", followUp: "What would need to change for your stress level to be manageable?" },

  // Opening
  { category: 'pornography', tags: [], phase: 'opening', content: "You're here. That matters more than you think. Whatever happened, we're going to look at it with curiosity — not judgment.", followUp: "How are you feeling right now, honestly?" },
  { category: 'pornography', tags: [], phase: 'opening', content: "Thanks for showing up. Most people run from this moment. You're choosing to face it. Let's start wherever you are.", followUp: "What brought you to the coach right now?" },

  // Affirmation
  { category: 'pornography', tags: [], phase: 'affirmation', content: "You showed up and told the truth. That's not nothing — that's the foundation everything else gets built on.", followUp: "" },
  { category: 'pornography', tags: [], phase: 'affirmation', content: "Freedom isn't found through perfection. It's found through honesty and kindness — toward yourself first.", followUp: "" },

  // ── SEXTING ───────────────────────────────────────────────
  { category: 'sexting', tags: [], phase: 'tributaries', content: "Sexting usually starts with a need to feel wanted, desired, or exciting to someone. What was happening emotionally before the conversation started?", followUp: "Were you feeling disconnected from someone close to you?" },
  { category: 'sexting', tags: ['loneliness'], phase: 'tributaries', content: "When you're lonely, a message from someone who seems interested can feel like oxygen. The pull toward that kind of attention makes sense — but it's worth asking what you're trading for it.", followUp: "What does the attention give you that you're not getting elsewhere?" },
  { category: 'sexting', tags: [], phase: 'longing', content: "Under the sexting is usually a longing to be desired, to matter to someone, to feel alive. Those are real needs. The question is whether this way of meeting them is building the life you want.", followUp: "What would it look like to feel desired in a way that doesn't cost you your integrity?" },
  { category: 'sexting', tags: [], phase: 'roadmap', content: "If you keep coming back to this, your pattern is saying: I need to feel wanted. That's not shameful — it's information. How could you build that feeling into relationships that are real?", followUp: "What's one relationship in your life worth investing more in?" },
  { category: 'sexting', tags: [], phase: 'opening', content: "This takes courage to look at honestly. Whatever happened, let's understand it together.", followUp: "What happened?" },
  { category: 'sexting', tags: [], phase: 'affirmation', content: "Choosing honesty about this — especially this — is an act of integrity. You're closer to the person you want to be than you feel.", followUp: "" },

  // ── ALCOHOL & DRUGS ───────────────────────────────────────
  { category: 'alcohol_drugs', tags: [], phase: 'tributaries', content: "Something happened before you reached for the drink or the substance. There's always a before. Let's find it.", followUp: "Walk me through your day — when did the urge first show up?" },
  { category: 'alcohol_drugs', tags: ['stress'], phase: 'tributaries', content: "When the pressure is too much and a drink promises to take the edge off, it makes sense. The question isn't whether the relief is real — it is, temporarily. The question is what the stress is actually about.", followUp: "What's weighing on you most right now?" },
  { category: 'alcohol_drugs', tags: ['conflict'], phase: 'tributaries', content: "After a fight, the nervous system is flooded. Alcohol or substances promise to quiet the noise. But the conflict will still be there tomorrow — plus the regret.", followUp: "What was the fight about, really?" },
  { category: 'alcohol_drugs', tags: ['loneliness'], phase: 'tributaries', content: "Drinking alone is often about filling a silence that feels unbearable. The substance becomes the companion. What would it look like to reach for a person instead?", followUp: "Who could you call right now?" },
  { category: 'alcohol_drugs', tags: [], phase: 'longing', content: "Beneath the substance is usually a longing for peace, for numbness, for things to stop being so hard for a minute. That need for relief is legitimate — the delivery mechanism is the problem.", followUp: "What would real rest feel like for you — without the substance?" },
  { category: 'alcohol_drugs', tags: [], phase: 'roadmap', content: "Your relationship with substances is telling you something about your relationship with pain. Not all pain needs to be numbed — some of it needs to be heard.", followUp: "What would change if you let yourself feel what you're avoiding?" },
  { category: 'alcohol_drugs', tags: [], phase: 'opening', content: "You're here, and that means something. Whether you used or you're on the edge, let's talk about what's happening.", followUp: "Where are you right now — did you use, or are you thinking about it?" },
  { category: 'alcohol_drugs', tags: [], phase: 'affirmation', content: "Every day you choose to face this honestly is a day you're building something real. Recovery isn't a straight line — it's a direction.", followUp: "" },

  // ── VAPING & TOBACCO ──────────────────────────────────────
  { category: 'vaping_tobacco', tags: [], phase: 'tributaries', content: "Nicotine is sneaky — the craving shows up and your brain tells you it's just physical. But there's usually something else. What's going on underneath the craving?", followUp: "When did the urge hit hardest today?" },
  { category: 'vaping_tobacco', tags: ['stress'], phase: 'tributaries', content: "Stress and nicotine are old friends. The vape promises a 30-second vacation from whatever's pressing on you. But 30 seconds later, the stress is still there and now you're frustrated with yourself too.", followUp: "What would actually help with the stress — not just pause it?" },
  { category: 'vaping_tobacco', tags: [], phase: 'longing', content: "The craving feels physical, but underneath it is often a need for a pause, a break, a moment of control in a day that feels out of control.", followUp: "What if you took the pause without the nicotine? What would that look like?" },
  { category: 'vaping_tobacco', tags: [], phase: 'roadmap', content: "You know this isn't the person you want to be. Every time you notice that gap between who you are and who you want to be — that's growth, not failure.", followUp: "What does freedom from nicotine look like for you?" },
  { category: 'vaping_tobacco', tags: [], phase: 'opening', content: "Nicotine is one of the hardest things to walk away from. Let's talk about what today looked like.", followUp: "How many times did you reach for it today?" },
  { category: 'vaping_tobacco', tags: [], phase: 'affirmation', content: "Every craving you sit with instead of acting on is rewiring your brain. It doesn't feel like progress in the moment, but it is.", followUp: "" },

  // ── ALCOHOL (substance-specific) ─────────────────────────
  { category: 'alcohol_drugs', tags: ['alcohol'], phase: 'tributaries', content: "The bottle promises relief but charges interest — every drink borrows peace from tomorrow to pay for numbness tonight. What happened today that made the trade feel worth it?", followUp: "What were you trying to stop feeling?" },
  { category: 'alcohol_drugs', tags: ['alcohol'], phase: 'longing', content: "Alcohol is the world's most socially accepted escape hatch. Everyone around you is pouring one, and you're supposed to just... not. The longing isn't for the drink — it's for the permission to stop carrying whatever you're carrying.", followUp: "What would you need to put down — emotionally — to not need the drink?" },

  // ── MARIJUANA (substance-specific) ───────────────────────
  { category: 'alcohol_drugs', tags: ['marijuana', 'cannabis'], phase: 'tributaries', content: "Cannabis numbs the edges, but the edges are where the growth happens. The sharp parts of your day — the anxiety, the boredom, the restlessness — are trying to tell you something. What are they saying?", followUp: "What does your day look like when you're not high?" },
  { category: 'alcohol_drugs', tags: ['marijuana', 'cannabis'], phase: 'longing', content: "The high makes everything feel softer, slower, more bearable. That's real. But so is the fog the next morning, and the goals that keep sliding. What are you reaching for underneath the smoke?", followUp: "What would your life look like with the clarity you keep trading away?" },

  // ── NICOTINE / VAPING (substance-specific) ───────────────
  { category: 'vaping_tobacco', tags: ['vaping', 'nicotine'], phase: 'tributaries', content: "The craving feels physical, but underneath it is a rhythm — a ritual your body expects. Step outside, inhale, exhale, feel something shift. What if the ritual could stay and the nicotine could go?", followUp: "When do you reach for it most — and what's happening right before?" },
  { category: 'vaping_tobacco', tags: ['vaping', 'nicotine'], phase: 'longing', content: "Nicotine promised you a pause button for life. Three minutes of nothing but you and the hit. But every pause gets shorter and the need gets louder. What would a real pause look like — one that doesn't come with a leash?", followUp: "What does freedom from nicotine look like in your daily life?" },
];
