import type { CoachingEntry } from './types';

export const COACHING_LIBRARY_OTHER: CoachingEntry[] = [
  // ── EATING DISORDER ───────────────────────────────────────
  { category: 'eating_disorder', tag: null, phase: 'tributaries', content: "The relationship with food and your body didn't start today. Something triggered the urge to restrict, purge, or binge. Let's trace it back gently.", followUp: "What happened today that made you feel out of control?" },
  { category: 'eating_disorder', tag: 'shame', phase: 'tributaries', content: "Shame about your body is one of the cruelest loops — it drives the behavior, then the behavior deepens the shame. You deserve better than that cycle.", followUp: "Whose voice do you hear when you look in the mirror?" },
  { category: 'eating_disorder', tag: null, phase: 'longing', content: "Under the food rules is usually a longing for control, safety, or worthiness. Those needs are legitimate — your body just became the battlefield.", followUp: "What would feeling safe in your own body feel like?" },
  { category: 'eating_disorder', tag: null, phase: 'roadmap', content: "Your body has carried you through everything you've survived. It's not the enemy — it's the home. What would it look like to treat it like one?", followUp: "What's one kind thing you could do for your body today?" },
  { category: 'eating_disorder', tag: null, phase: 'opening', content: "This is sensitive territory, and you're brave for looking at it. Let's go slowly.", followUp: "How are you feeling about food and your body right now?" },
  { category: 'eating_disorder', tag: null, phase: 'affirmation', content: "Healing your relationship with food and your body is some of the hardest work there is. You're doing it.", followUp: "" },

  // ── BODY CHECKING ─────────────────────────────────────────
  { category: 'body_checking', tag: null, phase: 'tributaries', content: "The mirror check, the scale, the measuring — it feels like information, but it's really reassurance-seeking. What made you need reassurance today?", followUp: "How many times did you check today?" },
  { category: 'body_checking', tag: null, phase: 'longing', content: "Under the checking is a longing to feel okay in your skin. To know you're enough without measuring. That longing is worth listening to.", followUp: "When was the last time you felt at peace with your body?" },
  { category: 'body_checking', tag: null, phase: 'roadmap', content: "What if your worth wasn't measured in inches or pounds? What would you measure it in instead?", followUp: "What makes you valuable that has nothing to do with how you look?" },
  { category: 'body_checking', tag: null, phase: 'opening', content: "Body checking can feel like a small thing, but you know it's become something bigger. Let's talk about it.", followUp: "What prompted the check today?" },
  { category: 'body_checking', tag: null, phase: 'affirmation', content: "Every time you choose not to check is a quiet act of rebellion against a culture that profits from your insecurity.", followUp: "" },

  // ── DATING APPS ───────────────────────────────────────────
  { category: 'dating_apps', tag: null, phase: 'tributaries', content: "The swipe is quick, but the need behind it isn't. What were you looking for when you opened the app — connection, validation, distraction?", followUp: "Were you hoping to find someone, or hoping to feel something?" },
  { category: 'dating_apps', tag: 'loneliness', phase: 'tributaries', content: "When you're lonely, a match feels like proof that you matter. But the dopamine from a match fades in seconds, and the loneliness is still there underneath.", followUp: "What kind of relationship are you actually looking for?" },
  { category: 'dating_apps', tag: null, phase: 'longing', content: "Under the compulsive swiping is a longing to be chosen, to be desired, to not be alone. Those are some of the most human needs there are.", followUp: "What would being truly known by someone feel like?" },
  { category: 'dating_apps', tag: null, phase: 'roadmap', content: "If you spent the same time you spend swiping on deepening one real relationship — a friendship, a family bond — what would change?", followUp: "Who in your life deserves more of your attention?" },
  { category: 'dating_apps', tag: null, phase: 'opening', content: "Dating apps are designed to be addictive. There's no shame in getting caught in the loop. Let's understand what's driving it.", followUp: "How much time did you spend swiping today?" },
  { category: 'dating_apps', tag: null, phase: 'affirmation', content: "Choosing to be present in your real life instead of swiping through possibilities — that's choosing depth over breadth.", followUp: "" },

  // ── IMPULSE SHOPPING ──────────────────────────────────────
  { category: 'impulse_shopping', tag: null, phase: 'tributaries', content: "The cart wasn't about what you were buying — it was about how buying it made you feel. What were you feeling before you started browsing?", followUp: "What emotion were you trying to buy your way out of?" },
  { category: 'impulse_shopping', tag: 'stress', phase: 'tributaries', content: "Retail therapy is real — dopamine spikes when you click 'buy.' But the high fades and the credit card statement doesn't. What stress were you medicating?", followUp: "What's the stress actually about?" },
  { category: 'impulse_shopping', tag: null, phase: 'longing', content: "Under the shopping is often a longing to feel in control, to treat yourself, to fill an emptiness that stuff can't fill. The packages arrive, but the emptiness stays.", followUp: "What would actually make you feel full?" },
  { category: 'impulse_shopping', tag: null, phase: 'roadmap', content: "Every purchase is a vote for the life you're building. Are you buying the life you want, or numbing the one you have?", followUp: "What's one thing money can't buy that you need more of?" },
  { category: 'impulse_shopping', tag: null, phase: 'opening', content: "Shopping isn't usually what people think of as a struggle — but you know it's become one. That honesty matters.", followUp: "What did you buy today, and how do you feel about it now?" },
  { category: 'impulse_shopping', tag: null, phase: 'affirmation', content: "Closing the cart instead of clicking checkout takes more willpower than people realize. You're building that muscle.", followUp: "" },

  // ── RAGE CONTENT ──────────────────────────────────────────
  { category: 'rage_content', tag: null, phase: 'tributaries', content: "Outrage is addictive — it gives you a target for feelings that might otherwise have nowhere to go. What were you feeling before the rage content pulled you in?", followUp: "What are you actually angry about — not the content, but in your life?" },
  { category: 'rage_content', tag: 'conflict', phase: 'tributaries', content: "After a conflict, rage content feels validating — someone else is angry too. But feeding the anger doesn't resolve the conflict. It just keeps your nervous system activated.", followUp: "Who are you actually in conflict with?" },
  { category: 'rage_content', tag: null, phase: 'longing', content: "Under the outrage is often a longing for justice, for things to make sense, for the world to be fair. Those longings are good — but comment sections aren't where justice lives.", followUp: "Where in your actual life can you make things better?" },
  { category: 'rage_content', tag: null, phase: 'roadmap', content: "If anger is your default emotion, it's usually covering something softer underneath — hurt, fear, sadness. Rage feels powerful; the thing beneath it feels vulnerable.", followUp: "What's the feeling underneath the anger?" },
  { category: 'rage_content', tag: null, phase: 'opening', content: "Getting pulled into outrage content is more common than people admit. Let's look at what's driving it.", followUp: "What kind of content were you consuming, and for how long?" },
  { category: 'rage_content', tag: null, phase: 'affirmation', content: "Choosing to step away from the outrage machine and deal with your own life takes more courage than firing off another comment.", followUp: "" },

  // ── UNIVERSAL TAG CONTENT ─────────────────────────────────
  { category: 'general', tag: 'late-night', phase: 'tributaries', content: "Late at night your defenses are down and your brain defaults to comfort-seeking. There's nothing wrong with you — but the choices you make at midnight rarely reflect who you want to be at noon.", followUp: "What would help you wind down differently tonight?" },
  { category: 'general', tag: 'stress', phase: 'tributaries', content: "Stress doesn't justify the behavior, but it explains it. When your nervous system is maxed out, it reaches for the fastest exit. Let's find what's maxing it out.", followUp: "What's weighing on you most?" },
  { category: 'general', tag: 'loneliness', phase: 'tributaries', content: "Loneliness drives more compulsive behavior than any other emotion. Your brain is wired for connection — when it can't find the real thing, it settles for substitutes.", followUp: "When did you last feel genuinely connected to someone?" },
  { category: 'general', tag: 'conflict', phase: 'tributaries', content: "After a conflict, your body is flooded with cortisol looking for an outlet. The behavior you turned to was your nervous system's attempt to regulate. Now let's deal with the actual conflict.", followUp: "What was the conflict about?" },
  { category: 'general', tag: 'exhaustion', phase: 'tributaries', content: "When you're running on empty, willpower is the first thing to go. This isn't weakness — it's biology. But it's also a signal that something about how you're living is unsustainable.", followUp: "What's draining you most?" },
  { category: 'general', tag: 'boredom', phase: 'tributaries', content: "Boredom is often restlessness in disguise — a life that doesn't have enough of what matters to you. The behavior fills the gap temporarily, but the gap remains.", followUp: "What used to excite you that you've stopped doing?" },
  { category: 'general', tag: 'rejection', phase: 'tributaries', content: "Rejection hits the same brain circuits as physical pain. When that pain shows up, you reach for relief. That's not weakness — it's wiring. But you can learn to sit with the sting.", followUp: "What happened? Who rejected you?" },
  { category: 'general', tag: 'shame', phase: 'tributaries', content: "Shame is the most isolating emotion there is — it tells you you're fundamentally broken, and that if anyone saw the real you, they'd leave. Shame lies. You're here proving it wrong.", followUp: "What are you most ashamed of right now?" },
  { category: 'general', tag: 'anger', phase: 'tributaries', content: "Anger is usually a bodyguard for a softer emotion underneath — hurt, fear, helplessness. The behavior you turned to was about the anger. Let's look at what the anger is about.", followUp: "What's underneath the anger?" },
  { category: 'general', tag: 'anxiety', phase: 'tributaries', content: "Anxiety is future-pain felt in the present. Your brain is running worst-case scenarios, and the behavior offered a way to hit pause on the projector. What's the movie your mind is playing?", followUp: "What are you most worried about?" },
  { category: 'general', tag: 'travel', phase: 'tributaries', content: "Travel disrupts your routines, your support systems, and your accountability structures. Hotel rooms are lonely. New cities are anonymous. Makes sense that old patterns resurface.", followUp: "What routine did travel disrupt that usually keeps you grounded?" },
  { category: 'general', tag: 'celebration', phase: 'tributaries', content: "It's counterintuitive, but celebrations can trigger relapses — the good feeling wants more good feeling, and boundaries get loose when the mood is high.", followUp: "What were you celebrating?" },
  { category: 'general', tag: 'weekend', phase: 'tributaries', content: "Weekends have less structure, more free time, and fewer people watching. That combination is high-risk for most patterns. What's your weekend routine look like?", followUp: "What could you do differently this weekend?" },
  { category: 'general', tag: 'morning', phase: 'tributaries', content: "How you start the morning sets the trajectory for the day. If the behavior is the first thing you reach for, it means you're waking up already needing something you're not getting.", followUp: "What would a morning that set you up for a good day look like?" },
  { category: 'general', tag: 'work', phase: 'tributaries', content: "Work stress, work boredom, work conflict — the behavior often lives in the margins of the workday. A bathroom break, a lunch scroll, an after-work wind-down that goes too far.", followUp: "When during the workday are you most vulnerable?" },

  // ── CRISIS CONTENT ────────────────────────────────────────
  { category: 'crisis', tag: null, phase: 'tributaries', content: "You're in real pain right now, and I hear you. This moment is heavy, but it will pass. You don't have to face this alone. Please reach out to someone who can help right now.", followUp: "Can you call or text someone you trust in the next 5 minutes?" },
  { category: 'crisis', tag: null, phase: 'longing', content: "What you're feeling right now is temporary, even though it doesn't feel that way. The pain is real, but it's not the whole story. You matter — not because of what you've done or haven't done, but because you're here.", followUp: "What's one thing worth staying for?" },
  { category: 'crisis', tag: null, phase: 'roadmap', content: "Crisis resources are available 24/7. You don't have to explain everything — just reach out. 988 Suicide & Crisis Lifeline: call or text 988. Crisis Text Line: text HOME to 741741.", followUp: "" },
  { category: 'crisis', tag: null, phase: 'opening', content: "I'm concerned about what you've shared. Before we go further, I want to make sure you're safe. If you're thinking about hurting yourself, please contact the 988 Suicide & Crisis Lifeline by calling or texting 988.", followUp: "Are you safe right now?" },
  { category: 'crisis', tag: null, phase: 'affirmation', content: "Reaching out when you're in this much pain is one of the bravest things a person can do. You are not alone. 988 is there 24/7. So is Crisis Text Line — text HOME to 741741.", followUp: "" },

  // ── GENERAL FALLBACK ──────────────────────────────────────
  { category: 'general', tag: null, phase: 'opening', content: "You're here, and that matters. Whatever brought you to this moment, we're going to look at it together — with curiosity, not judgment.", followUp: "What's on your mind?" },
  { category: 'general', tag: null, phase: 'opening', content: "Something happened, or something's about to happen, and you chose to come here instead of acting on autopilot. That's already a different choice than last time.", followUp: "What's going on?" },
  { category: 'general', tag: null, phase: 'affirmation', content: "You showed up. You were honest. That's the work. Everything else builds on this foundation.", followUp: "" },
  { category: 'general', tag: null, phase: 'affirmation', content: "Progress isn't a straight line — it's a direction. And right now, you're pointed the right way.", followUp: "" },
  { category: 'general', tag: null, phase: 'roadmap', content: "Your patterns are a map. They're not showing you what's wrong with you — they're showing you where your life needs attention.", followUp: "What does your pattern keep pointing to?" },
  { category: 'general', tag: null, phase: 'roadmap', content: "Imagine telling your future self about this moment. What would you want them to know you chose?", followUp: "What choice would make you proud tomorrow morning?" },
  { category: 'general', tag: null, phase: 'longing', content: "Every struggle has a legitimate need underneath it. Not the behavior — but the ache that drove you to it. Name the ache.", followUp: "What did you actually need in that moment?" },
  { category: 'general', tag: null, phase: 'longing', content: "You were reaching for something real — belonging, rest, significance, tenderness. The method was wrong, but the longing was right. Let's honor the longing.", followUp: "Which of those words resonates most: belonging, rest, significance, or tenderness?" },
];
