import type { CoachingEntry } from './types';

export const COACHING_LIBRARY_DIGITAL_GAMBLING: CoachingEntry[] = [
  // ── SOCIAL MEDIA ──────────────────────────────────────────
  { category: 'social_media', tags: [], phase: 'tributaries', content: "The scroll started somewhere. Before you opened the app, something was happening — or not happening — that made the feed feel necessary.", followUp: "What were you avoiding when you picked up your phone?" },
  { category: 'social_media', tags: ['loneliness'], phase: 'tributaries', content: "Social media promises connection but usually delivers comparison. When you're lonely, the feed feels like company — but it's a room full of people who can't see you.", followUp: "Who do you wish you were actually talking to right now?" },
  { category: 'social_media', tags: ['stress'], phase: 'tributaries', content: "Scrolling when you're stressed is your brain's way of dissociating — checking out without checking out. The relief is real but temporary, and the stress is still there when you look up.", followUp: "What's the stress actually about?" },
  { category: 'social_media', tags: ['boredom'], phase: 'tributaries', content: "Boredom and your phone have become a reflex — there's barely a thought between the feeling and the unlock. What if the boredom is trying to tell you something about how you're spending your time?", followUp: "If you couldn't scroll, what would you actually want to do?" },
  { category: 'social_media', tags: ['late-night'], phase: 'tributaries', content: "Late-night scrolling is often about not wanting to be alone with your own thoughts. The feed fills the silence. But the silence has something to say.", followUp: "What thoughts are you avoiding by staying on your phone?" },
  { category: 'social_media', tags: [], phase: 'longing', content: "Under the endless scroll is usually a longing to feel connected, informed, or relevant. Those needs are real — but the feed can't meet them. It can only simulate meeting them.", followUp: "What would real connection look like for you today?" },
  { category: 'social_media', tags: [], phase: 'roadmap', content: "If your phone is the first thing you reach for and the last thing you put down, your life is organized around a screen. What would a day look like if it was organized around what actually matters to you?", followUp: "What's one thing you'd do differently tomorrow morning?" },
  { category: 'social_media', tags: [], phase: 'opening', content: "Screen time can feel like a small thing, but you're here because part of you knows it's not small anymore. Let's look at what's happening.", followUp: "How much time did you spend scrolling today?" },
  { category: 'social_media', tags: [], phase: 'affirmation', content: "Noticing the pattern is the first step. Most people never even get here — they just keep scrolling. You stopped.", followUp: "" },

  // ── BINGE WATCHING ────────────────────────────────────────
  { category: 'binge_watching', tags: [], phase: 'tributaries', content: "One episode turns into five because stopping means re-entering your actual life. What's in your actual life right now that the show is helping you escape?", followUp: "What were you putting off when you hit 'next episode'?" },
  { category: 'binge_watching', tags: ['exhaustion'], phase: 'tributaries', content: "When you're exhausted, the couch and the remote feel earned. And sometimes they are. But when it becomes the default every night, it's worth asking: is this rest, or is this avoidance?", followUp: "What would actual rest look like — not just numbing out?" },
  { category: 'binge_watching', tags: ['loneliness'], phase: 'tributaries', content: "Characters on screen can feel like company. The show gives you people to care about without the vulnerability of real relationships. That makes sense — but it's a one-way street.", followUp: "When's the last time you spent an evening with a real person?" },
  { category: 'binge_watching', tags: [], phase: 'longing', content: "Under the binge is usually a need to disappear for a while — from responsibility, from pain, from the gap between where you are and where you want to be.", followUp: "What would you need for that gap to feel smaller?" },
  { category: 'binge_watching', tags: [], phase: 'roadmap', content: "Your evenings tell the story of your priorities. Not what you say matters — what you actually do with your unstructured time. What story do you want your evenings to tell?", followUp: "What's one evening this week you could reclaim?" },
  { category: 'binge_watching', tags: [], phase: 'opening', content: "There's no shame in watching TV. The question is whether it's a choice or a default. Let's figure out which one it was today.", followUp: "How many hours did you watch?" },
  { category: 'binge_watching', tags: [], phase: 'affirmation', content: "Being honest about how you spend your time is harder than it sounds. You're paying attention now, and that changes everything.", followUp: "" },

  // ── GAMBLING ──────────────────────────────────────────────
  { category: 'gambling', tags: [], phase: 'tributaries', content: "The bet wasn't random. Something made the risk feel worth it — or made you stop caring about the consequences. What was happening before you placed it?", followUp: "What were you feeling right before you opened the app?" },
  { category: 'gambling', tags: ['stress'], phase: 'tributaries', content: "When life feels out of control, a bet offers the illusion of control — the chance to make something happen. But the house always has the edge, and the stress doesn't go away.", followUp: "What's feeling out of control in your life right now?" },
  { category: 'gambling', tags: ['boredom'], phase: 'tributaries', content: "Gambling turns boredom into adrenaline in seconds. That dopamine hit is real — and your brain remembers it. But boredom might be telling you your life needs more meaning, not more risk.", followUp: "What's missing that gambling is filling?" },
  { category: 'gambling', tags: ['anger'], phase: 'tributaries', content: "Chasing losses is often about anger — at yourself, at the situation, at the feeling of being behind. The next bet feels like it'll make things right. It won't.", followUp: "What are you actually angry about?" },
  { category: 'gambling', tags: [], phase: 'longing', content: "Under the gambling is usually a longing for excitement, for a shortcut, for proof that you're lucky or special or that things will turn around. Those feelings are human — the delivery method is the problem.", followUp: "What would 'things turning around' actually look like without the bet?" },
  { category: 'gambling', tags: [], phase: 'roadmap', content: "If you keep chasing the win, ask yourself: what would winning even solve? If you won big tonight, what would you actually do with it? That answer tells you what you really want.", followUp: "What do you really want that money can't buy?" },
  { category: 'gambling', tags: [], phase: 'opening', content: "Gambling is one of the hardest patterns to break because the brain treats near-misses like wins. Let's talk about what happened.", followUp: "Did you bet today, or are you thinking about it?" },
  { category: 'gambling', tags: [], phase: 'affirmation', content: "Every day you don't bet is a day you chose your future over a dopamine hit. That's not small.", followUp: "" },

  // ── SPORTS BETTING ────────────────────────────────────────
  { category: 'sports_betting', tags: [], phase: 'tributaries', content: "Sports betting wraps gambling in something that feels like skill and knowledge. But the trigger isn't about the game — it's about what the bet does for you emotionally.", followUp: "Was it the game you wanted, or the action?" },
  { category: 'sports_betting', tags: ['stress'], phase: 'tributaries', content: "A bet turns a game into something that matters — something that distracts from whatever else is weighing on you. For 3 hours, the stress has somewhere else to go.", followUp: "What stress were you escaping?" },
  { category: 'sports_betting', tags: [], phase: 'longing', content: "The bet makes you feel like you're in the game, like your knowledge matters, like you have an edge. That longing for mastery and relevance is real — but it belongs in your actual life, not a sportsbook.", followUp: "Where in your real life do you feel like your knowledge and effort matter?" },
  { category: 'sports_betting', tags: [], phase: 'roadmap', content: "If you spent the same energy you put into lines, odds, and parlays into something you're building — what could you create?", followUp: "What's one thing worth that level of attention?" },
  { category: 'sports_betting', tags: [], phase: 'opening', content: "Let's talk about the bet. No judgment — just understanding.", followUp: "What did you bet on today?" },
  { category: 'sports_betting', tags: [], phase: 'affirmation', content: "Walking away from the sportsbook when every ad, every friend, and every notification is pulling you in — that takes real strength.", followUp: "" },

  // ── DAY TRADING ───────────────────────────────────────────
  { category: 'day_trading', tags: [], phase: 'tributaries', content: "Trading looks like productivity, but compulsive trading is gambling wearing a suit. What drove you to the screen today — strategy, or something else?", followUp: "Were you following a plan, or reacting to emotions?" },
  { category: 'day_trading', tags: ['anxiety'], phase: 'tributaries', content: "Watching charts all day keeps your nervous system in fight-or-flight. The anxiety you feel isn't just about the market — the market is amplifying whatever anxiety was already there.", followUp: "If you stepped away from the screen, what would you have to face?" },
  { category: 'day_trading', tags: [], phase: 'longing', content: "Trading often fills a longing for control, for proof of intelligence, for financial freedom. Those are good goals — but compulsive trading rarely achieves them.", followUp: "What would financial peace actually look like for you?" },
  { category: 'day_trading', tags: [], phase: 'roadmap', content: "The market will be there tomorrow. Your relationships, your health, your presence — those have expiration dates. What's the trade-off you're actually making?", followUp: "How many hours did you spend watching charts today vs being present with people?" },
  { category: 'day_trading', tags: [], phase: 'opening', content: "Trading can feel productive even when it's destructive. Let's look at today honestly.", followUp: "Did you stick to your rules today, or did you chase?" },
  { category: 'day_trading', tags: [], phase: 'affirmation', content: "Recognizing that the trading has become compulsive — not strategic — is the hardest and most honest thing a trader can do.", followUp: "" },

  // ── GAMING ────────────────────────────────────────────────
  { category: 'gaming', tags: [], phase: 'tributaries', content: "Gaming gives you a world where your effort matters, where progress is clear, and where you have control. That's appealing — especially when real life feels the opposite.", followUp: "What's happening in your real life that the game is better than?" },
  { category: 'gaming', tags: ['loneliness'], phase: 'tributaries', content: "Online friends feel real — and in many ways they are. But if gaming is your only source of connection, you're building a social life inside a screen that can't hold you when things get hard.", followUp: "Do you have people in your physical life who know you?" },
  { category: 'gaming', tags: ['stress'], phase: 'tributaries', content: "Gaming after a hard day feels earned. And sometimes it is. But when 'one game' turns into 4 hours and you're up at 2 AM — the stress relief has become its own source of stress.", followUp: "How many hours was it today?" },
  { category: 'gaming', tags: ['boredom'], phase: 'tributaries', content: "Games are engineered to be more interesting than real life. That's not a fair fight. But real life is where your story actually happens.", followUp: "What's one thing in your real life that used to excite you?" },
  { category: 'gaming', tags: [], phase: 'longing', content: "Under the gaming is usually a need for achievement, mastery, or escape. In the game, your rank matters. Your effort pays off. Your skill is visible. What if those things were true in your actual life too?", followUp: "Where in your real life do you want to level up?" },
  { category: 'gaming', tags: [], phase: 'roadmap', content: "You've put thousands of hours into virtual worlds. Imagine if even 20% of that went into something you're building in real life. What would you build?", followUp: "What's one real-world skill worth grinding?" },
  { category: 'gaming', tags: [], phase: 'opening', content: "Gaming isn't the enemy — but you're here because something about it has stopped being fun and started being compulsive. Let's figure out the line.", followUp: "When did gaming stop being a choice and start being a default?" },
  { category: 'gaming', tags: [], phase: 'affirmation', content: "Stepping away from the game to look at your life honestly? That's a bigger achievement than any raid clear.", followUp: "" },
];
